version: '1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "6001:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: finance-control-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
