version: '1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "6000:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: DMS
    volumes:
      - ./postgres:/var/lib/postgresql/data